// Generated by CoffeeScript 1.7.1
(function() {
  var DisplayBlockdataPlugin;

  module.exports = function(game, opts) {
    return new DisplayBlockdataPlugin(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['voxel-highlight', 'voxel-blockdata'],
    clientOnly: true
  };

  DisplayBlockdataPlugin = (function() {
    function DisplayBlockdataPlugin(game, opts) {
      var _ref, _ref1;
      this.game = game;
      this.hl = (function() {
        var _ref1;
        if ((_ref = (_ref1 = this.game.plugins) != null ? _ref1.get('voxel-highlight') : void 0) != null) {
          return _ref;
        } else {
          throw 'voxel-display-blockdata requires voxel-highlight plugin';
        }
      }).call(this);
      this.blockdata = (_ref1 = this.game.plugins) != null ? _ref1.get('voxel-blockdata') : void 0;
      this.createNode();
      this.enable();
    }

    DisplayBlockdataPlugin.prototype.createNode = function() {
      this.node = document.createElement('div');
      this.node.setAttribute('id', 'voxel-display-blockdata');
      this.node.setAttribute('style', 'border: 1px solid black; background-image: linear-gradient(rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.6) 100%); position: absolute; visibility: hidden; top: 0px; left: 50%; color: white; font-size: 18pt;');
      this.node.textContent = '';
      return document.body.appendChild(this.node);
    };

    DisplayBlockdataPlugin.prototype.update = function(pos) {
      var bd, content, x, y, z;
      this.lastPos = pos;
      if (this.lastPos == null) {
        this.clear();
        return;
      }
      if (this.blockdata != null) {
        x = pos[0], y = pos[1], z = pos[2];
        bd = this.blockdata.get(x, y, z);
        if (bd != null) {
          content = "" + (JSON.stringify(bd));
          window.status = content;
          return this.node.textContent = content;
        }
      }
    };

    DisplayBlockdataPlugin.prototype.clear = function() {
      this.lastPos = void 0;
      return this.node.textContent = '';
    };

    DisplayBlockdataPlugin.prototype.enable = function() {
      this.node.style.visibility = '';
      this.hl.on('highlight', this.onHighlight = (function(_this) {
        return function(pos) {
          return _this.update(pos);
        };
      })(this));
      this.hl.on('remove', this.onRemove = (function(_this) {
        return function() {
          return _this.clear();
        };
      })(this));
      if (this.game.buttons.changed != null) {
        return this.game.buttons.changed.on('crouch', this.onChanged = (function(_this) {
          return function() {
            return _this.update(_this.lastPos);
          };
        })(this));
      }
    };

    DisplayBlockdataPlugin.prototype.disable = function() {
      this.hl.removeListener('highlight', this.onHighlight);
      this.hl.removeListener('remove', this.onRemove);
      if (this.game.buttons.changed != null) {
        this.game.buttons.changed.removeListener('crouch', this.onChanged);
      }
      return this.node.style.visibility = 'hidden';
    };

    return DisplayBlockdataPlugin;

  })();

}).call(this);
